name: BetterTPA
version: '1.0-SNAPSHOT'
main: com.gliesestudio.mc.BetterTPA
api-version: '1.21'
authors: [ Mazidul Islam ]
description: Better TPA is the goto plugin to manage player tpa and set warps with ease.
website: https://mazidul.com

commands:
  tpa:
    description: Request to teleport to another player.
    usage: /tpa <player>
  tphere:
    description: Request to teleport another player to you.
    usage: /tphere <player>
  tpaccept:
    description: Accept a teleport request.
    usage: /tpaccept
    aliases:
      - accept
  tpdeny:
    description: Deny a teleport request.
    usage: /tpdeny
    aliases:
      - deny
  back:
    description: Teleport back to your last death or TPA location
    usage: /back
    aliases:
      - tpback

  setwarp:
    description: Set a warp location.
    usage: /setwarp <name>

  warp:
    description: Teleport to a warp.
    usage: /warp <name>

  warps:
    description: List available warps.
    usage: /warps

  delwarp:
    description: Delete a warp location.
    usage: /delwarp <name>
    permission: bettertpa.delwarp # Add a permission node
    permission-message: §cYou don't have permission to use this command.