name: Build and Release JAR

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get project version and jar file name
        id: get_version
        run: |
          PROJECT_NAME=$(./gradlew -q projectName) # You may need a task to print the project name if not directly available
          VERSION=$(./gradlew -q printVersion)      # Run a custom Gradle task to print the version
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "JAR_NAME=${PROJECT_NAME}-${VERSION}.jar" >> $GITHUB_ENV

      - name: Build project with Gradle
        run: ./gradlew build

      - name: Upload JAR file to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/${{ env.JAR_NAME }}
          asset_name: ${{ env.JAR_NAME }}
          asset_content_type: application/java-archive
